
name: Build Android APK
on:
  workflow_dispatch:
  repository_dispatch:
    types: [build-apk]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Android APK
        uses: pwa-builder/pwa-starter-action@v1.3
        with:
          pwa-url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          android-package-id: "com.jfl.gigawall"
          android-app-name: "Giga Wall JFL"
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: giga-wall-apk
          path: ./*.apk
