# .github/workflows/deploy.yml
name: Giga Wall Deploy
on:
  repository_dispatch:
    types: [giga_wall_deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Signal Received
        run: echo "Plataforma JFL solicitou build autom√°tico!"
